"""
Mood constants and utilities (migrated from shared/moods.js)
"""

MOODS = {
    "OVERJOYED": {
        "id": "overjoyed",
        "label": "Overjoyed",
        "emoji": "🤗",
        "score": 10,
        "color": "yellow",
        "prompt": "What wonderful things happened today?",
        "pixabay_query": "joyful+celebration+happy",
    },
    "ACCOMPLISHED": {
        "id": "accomplished",
        "label": "Accomplished",
        "emoji": "⭐",
        "score": 9,
        "color": "amber",
        "prompt": "What have you achieved?",
        "pixabay_query": "achievement+success+star",
    },
    "INSPIRED": {
        "id": "inspired",
        "label": "Inspired",
        "emoji": "💫",
        "score": 9,
        "color": "violet",
        "prompt": "What's sparking your creativity?",
        "pixabay_query": "inspiration+creative+light",
    },
    "PROUD": {
        "id": "proud",
        "label": "Proud",
        "emoji": "🦁",
        "score": 9,
        "color": "amber",
        "prompt": "What achievement are you proud of?",
        "pixabay_query": "achievement+success+proud",
    },
    "LOVED": {
        "id": "loved",
        "label": "Loved",
        "emoji": "🥰",
        "score": 9,
        "color": "pink",
        "prompt": "Who or what is making you feel loved?",
        "pixabay_query": "love+heart+affection",
    },
    "APPRECIATED": {
        "id": "appreciated",
        "label": "Appreciated",
        "emoji": "💝",
        "score": 8,
        "color": "pink",
        "prompt": "How do you feel appreciated today?",
        "pixabay_query": "gratitude+appreciation+thanks",
    },
    "HAPPY": {
        "id": "happy",
        "label": "Happy",
        "emoji": "😊",
        "score": 8,
        "color": "yellow",
        "prompt": "What's bringing you joy?",
        "pixabay_query": "happiness+smile+joy",
    },
    "CONTENT": {
        "id": "content",
        "label": "Content",
        "emoji": "😌",
        "score": 7,
        "color": "green",
        "prompt": "What's giving you peace today?",
        "pixabay_query": "peaceful+content+calm",
    },
    "HOPEFUL": {
        "id": "hopeful",
        "label": "Hopeful",
        "emoji": "🌅",
        "score": 7,
        "color": "orange",
        "prompt": "What are you looking forward to?",
        "pixabay_query": "hope+sunrise+future",
    },
    "GRATEFUL": {
        "id": "grateful",
        "label": "Grateful",
        "emoji": "🙏",
        "score": 8,
        "color": "amber",
        "prompt": "What are you thankful for?",
        "pixabay_query": "gratitude+thankful+blessing",
    },
    "EXCITED": {
        "id": "excited",
        "label": "Excited",
        "emoji": "🎉",
        "score": 8,
        "color": "yellow",
        "prompt": "What's got you excited?",
        "pixabay_query": "excitement+celebration+energy",
    },
    "RELAXED": {
        "id": "relaxed",
        "label": "Relaxed",
        "emoji": "🧘",
        "score": 7,
        "color": "blue",
        "prompt": "How are you finding peace?",
        "pixabay_query": "relaxation+meditation+calm",
    },
    "OPTIMISTIC": {
        "id": "optimistic",
        "label": "Optimistic",
        "emoji": "🌈",
        "score": 7,
        "color": "violet",
        "prompt": "What's looking bright?",
        "pixabay_query": "optimism+rainbow+positive",
    },
    "NEUTRAL": {
        "id": "neutral",
        "label": "Neutral",
        "emoji": "😐",
        "score": 5,
        "color": "gray",
        "prompt": "How was your day overall?",
        "pixabay_query": "neutral+balance+calm",
    },
    "TIRED": {
        "id": "tired",
        "label": "Tired",
        "emoji": "😴",
        "score": 4,
        "color": "blue",
        "prompt": "What's been draining your energy?",
        "pixabay_query": "tired+exhausted+rest",
    },
    "STRESSED": {
        "id": "stressed",
        "label": "Stressed",
        "emoji": "😰",
        "score": 3,
        "color": "red",
        "prompt": "What's causing you stress?",
        "pixabay_query": "stress+pressure+overwhelmed",
    },
    "ANXIOUS": {
        "id": "anxious",
        "label": "Anxious",
        "emoji": "😟",
        "score": 3,
        "color": "yellow",
        "prompt": "What's making you feel anxious?",
        "pixabay_query": "anxiety+worry+concern",
    },
    "FRUSTRATED": {
        "id": "frustrated",
        "label": "Frustrated",
        "emoji": "😤",
        "score": 3,
        "color": "orange",
        "prompt": "What's frustrating you?",
        "pixabay_query": "frustration+anger+irritated",
    },
    "SAD": {
        "id": "sad",
        "label": "Sad",
        "emoji": "😢",
        "score": 2,
        "color": "blue",
        "prompt": "What's weighing on your heart?",
        "pixabay_query": "sadness+melancholy+blue",
    },
    "LONELY": {
        "id": "lonely",
        "label": "Lonely",
        "emoji": "😔",
        "score": 2,
        "color": "gray",
        "prompt": "Tell me about feeling alone.",
        "pixabay_query": "loneliness+solitude+alone",
    },
    "OVERWHELMED": {
        "id": "overwhelmed",
        "label": "Overwhelmed",
        "emoji": "😵",
        "score": 2,
        "color": "red",
        "prompt": "What feels like too much right now?",
        "pixabay_query": "overwhelmed+chaos+too+much",
    },
    "ANGRY": {
        "id": "angry",
        "label": "Angry",
        "emoji": "😡",
        "score": 2,
        "color": "red",
        "prompt": "What triggered your anger?",
        "pixabay_query": "anger+rage+fury",
    },
    "DISAPPOINTED": {
        "id": "disappointed",
        "label": "Disappointed",
        "emoji": "😞",
        "score": 3,
        "color": "gray",
        "prompt": "What didn't go as expected?",
        "pixabay_query": "disappointment+letdown+unmet",
    },
    "CONFUSED": {
        "id": "confused",
        "label": "Confused",
        "emoji": "😕",
        "score": 4,
        "color": "purple",
        "prompt": "What's unclear to you right now?",
        "pixabay_query": "confusion+uncertain+unclear",
    },
    "BORED": {
        "id": "bored",
        "label": "Bored",
        "emoji": "😑",
        "score": 4,
        "color": "gray",
        "prompt": "What would make things more interesting?",
        "pixabay_query": "boredom+dull+uninteresting",
    },
    "WORRIED": {
        "id": "worried",
        "label": "Worried",
        "emoji": "😨",
        "score": 3,
        "color": "yellow",
        "prompt": "What concerns are on your mind?",
        "pixabay_query": "worry+concern+fear",
    },
    "JEALOUS": {
        "id": "jealous",
        "label": "Jealous",
        "emoji": "😒",
        "score": 3,
        "color": "green",
        "prompt": "What's triggering these feelings?",
        "pixabay_query": "jealousy+envy+comparison",
    },
    "GUILTY": {
        "id": "guilty",
        "label": "Guilty",
        "emoji": "😳",
        "score": 3,
        "color": "red",
        "prompt": "What's causing you to feel guilty?",
        "pixabay_query": "guilt+regret+shame",
    },
    "EMBARRASSED": {
        "id": "embarrassed",
        "label": "Embarrassed",
        "emoji": "😳",
        "score": 3,
        "color": "pink",
        "prompt": "What made you feel embarrassed?",
        "pixabay_query": "embarrassment+shame+awkward",
    },
    "NOSTALGIC": {
        "id": "nostalgic",
        "label": "Nostalgic",
        "emoji": "🥺",
        "score": 6,
        "color": "purple",
        "prompt": "What memories are you reflecting on?",
        "pixabay_query": "nostalgia+memories+past",
    },
    "SURPRISED": {
        "id": "surprised",
        "label": "Surprised",
        "emoji": "😲",
        "score": 6,
        "color": "yellow",
        "prompt": "What caught you off guard?",
        "pixabay_query": "surprise+unexpected+shock",
    },
    "CURIOUS": {
        "id": "curious",
        "label": "Curious",
        "emoji": "🤔",
        "score": 6,
        "color": "blue",
        "prompt": "What's piquing your interest?",
        "pixabay_query": "curiosity+wonder+question",
    },
    "DETERMINED": {
        "id": "determined",
        "label": "Determined",
        "emoji": "💪",
        "score": 8,
        "color": "orange",
        "prompt": "What are you working towards?",
        "pixabay_query": "determination+strength+focus",
    },
    "CONFIDENT": {
        "id": "confident",
        "label": "Confident",
        "emoji": "😎",
        "score": 8,
        "color": "blue",
        "prompt": "What's boosting your confidence?",
        "pixabay_query": "confidence+self+assured+strong",
    },
    "PLAYFUL": {
        "id": "playful",
        "label": "Playful",
        "emoji": "😜",
        "score": 7,
        "color": "pink",
        "prompt": "What's bringing out your playful side?",
        "pixabay_query": "playful+fun+lighthearted",
    },
    "CREATIVE": {
        "id": "creative",
        "label": "Creative",
        "emoji": "🎨",
        "score": 7,
        "color": "purple",
        "prompt": "What's inspiring your creativity?",
        "pixabay_query": "creativity+art+imagination",
    },
    "FOCUSED": {
        "id": "focused",
        "label": "Focused",
        "emoji": "🎯",
        "score": 7,
        "color": "green",
        "prompt": "What has your complete attention?",
        "pixabay_query": "focus+concentration+target",
    },
    "PEACEFUL": {
        "id": "peaceful",
        "label": "Peaceful",
        "emoji": "☮️",
        "score": 7,
        "color": "green",
        "prompt": "What's bringing you inner peace?",
        "pixabay_query": "peace+serenity+tranquil",
    },
    "ENERGETIC": {
        "id": "energetic",
        "label": "Energetic",
        "emoji": "⚡",
        "score": 8,
        "color": "yellow",
        "prompt": "What's fueling your energy?",
        "pixabay_query": "energy+vibrant+dynamic",
    },
    "MOTIVATED": {
        "id": "motivated",
        "label": "Motivated",
        "emoji": "🔥",
        "score": 8,
        "color": "orange",
        "prompt": "What's driving your motivation?",
        "pixabay_query": "motivation+drive+ambition",
    },
    "REFLECTIVE": {
        "id": "reflective",
        "label": "Reflective",
        "emoji": "🪞",
        "score": 6,
        "color": "blue",
        "prompt": "What are you contemplating?",
        "pixabay_query": "reflection+contemplation+thoughtful",
    },
    "MELANCHOLIC": {
        "id": "melancholic",
        "label": "Melancholic",
        "emoji": "🌧️",
        "score": 4,
        "color": "gray",
        "prompt": "What's creating this bittersweet feeling?",
        "pixabay_query": "melancholy+bittersweet+pensive",
    },
}


def get_mood_by_id(mood_id: str) -> dict:
    """
    Get mood data by ID
    """
    for mood_data in MOODS.values():
        if mood_data["id"] == mood_id:
            return mood_data
    return None


def get_mood_by_key(mood_key: str) -> dict:
    """
    Get mood data by key (uppercase)
    """
    return MOODS.get(mood_key.upper())


def get_all_moods() -> dict:
    """
    Get all moods
    """
    return MOODS
